# -*- coding: utf-8 -*-
"""sample_mean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ze0STHVbORKTERmsvFfW5G2cebWvA0rl
"""

import numpy as np
from scipy import stats

# Set random seed for reproducibility
np.random.seed(10)

# Parameters
sample_size = 30  # assumed sample size
sample_mean_pop = 50  # assumed population mean
alpha = 0.05  # significance level

# Generate the random sample from N(52, 8)
sample = np.random.normal(loc=52, scale=8, size=sample_size)

# Perform one-sample t-test
t_stat, p_value = stats.ttest_1samp(sample, sample_mean_pop)

# Report results
print(f"Sample Mean: {np.mean(sample):.4f}")
print(f"Population Mean: {sample_mean_pop}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")

# Conclusion at significance level alpha
if p_value < alpha:
    print(f"Since p-value ({p_value:.4f}) < {alpha}, we reject the null hypothesis.")
    print("The sample mean is significantly different from the population mean.")
else:
    print(f"Since p-value ({p_value:.4f}) >= {alpha}, we fail to reject the null hypothesis.")
    print("The sample mean is not significantly different from the population mean.")