# -*- coding: utf-8 -*-
"""t_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyZE44dWm8SJvoKkvkjP7EQw_8a0jRd4
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Dataset 1: Energy Bar Weights
energy_weights = [
    49.5, 50.2, 48.7, 51.1, 49.9, 50.5, 49.8, 50.3, 49.7, 50.6,
    50.1, 49.4, 50.0, 49.6, 50.8, 49.3, 50.4, 50.7, 49.2, 50.9
]

# Dataset 2: Teaching Methods
method_A = [78, 85, 82, 90, 76, 88, 84, 79, 91, 77]
method_B = [72, 81, 79, 74, 69, 83, 78, 75, 80, 71]

# Histogram & QQ plot
sns.histplot(energy_weights, kde=True)
plt.title("Histogram - Energy Bar Weights")
plt.xlabel("Weight (grams)")
plt.show()

stats.probplot(energy_weights, dist="norm", plot=plt)
plt.title("QQ Plot - Energy Bar Weights")
plt.show()

t_stat, p_val = stats.ttest_1samp(energy_weights, popmean=50)
print("One-Sample t-test:")
print(f"t-statistic = {t_stat:.4f}, p-value = {p_val:.4f}")

# Histograms
sns.histplot(method_A, kde=True, color='blue', label='Method A')
sns.histplot(method_B, kde=True, color='orange', label='Method B')
plt.title("Histogram - Student Scores")
plt.legend()
plt.show()

# QQ plots
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
stats.probplot(method_A, dist="norm", plot=ax[0])
ax[0].set_title("QQ Plot - Method A")

stats.probplot(method_B, dist="norm", plot=ax[1])
ax[1].set_title("QQ Plot - Method B")
plt.show()

t_stat2, p_val2 = stats.ttest_ind(method_A, method_B, equal_var=True)
print("Two-Sample t-test:")
print(f"t-statistic = {t_stat2:.4f}, p-value = {p_val2:.4f}")